Parameters:
  TrailName:
    Type: String
    Default: "CFN-test-6"
  BucketName:
    Type: String
    Default: newdemolevel

Resources:
  Trail:
    Type: AWS::CloudTrail::Trail
    Properties:
      S3BucketName: !Ref BucketName
      IsLogging: true
      TrailName: !Ref TrailName
      EnableLogFileValidation: true
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: true
